In [12]:
import pandas as pd

era5 = pd.read_csv(
    "/kaggle/input/datasets/arkalibaig/karakoram-era5-climate-dataset/gb_weather_corrected.csv"
)
era5.head(40)

,date,era5_period,station,district,lat,lon,elevation_m,temperature_2m_max,temperature_2m_min,temperature_2m_mean,...,et0_fao_evapotranspiration,sunshine_duration,daylight_duration,cloud_cover_mean,sunrise,sunset,weather_code,bias_corrected,month,year
0,1990-01-01,pre_2016,Chilas,Diamer,35.42,74.1,1250,8.66,5.70,6.90,...,1.14,24072.38,35307.29,85.14,1990-01-01 07:12:00,1990-01-01 17:01:00,71,0,1,1990
1,1990-01-02,pre_2016,Chilas,Diamer,35.42,74.1,1250,8.36,5.50,6.70,...,1.24,26205.91,35342.99,87.14,1990-01-02 07:13:00,1990-01-02 17:02:00,71,0,1,1990
2,1990-01-03,pre_2016,Chilas,Diamer,35.42,74.1,1250,8.36,6.40,7.50,...,0.96,1818.02,35381.64,92.14,1990-01-03 07:13:00,1990-01-03 17:02:00,73,0,1,1990
3,1990-01-04,pre_2016,Chilas,Diamer,35.42,74.1,1250,8.76,5.00,7.80,...,1.20,33518.04,35423.17,71.14,1990-01-04 07:13:00,1990-01-04 17:03:00,73,0,1,1990
4,1990-01-05,pre_2016,Chilas,Diamer,35.42,74.1,1250,4.66,0.30,2.70,...,1.25,34727.86,35467.52,52.14,1990-01-05 07:13:00,1990-01-05 17:04:00,71,0,1,1990
5,1990-01-06,pre_2016,Chilas,Diamer,35.42,74.1,1250,6.76,4.20,5.70,...,0.97,872.29,35514.62,89.14,1990-01-06 07:13:00,1990-01-06 17:05:00,73,0,1,1990
6,1990-01-07,pre_2016,Chilas,Diamer,35.42,74.1,1250,8.16,5.50,6.60,...,1.31,33882.08,35564.44,44.14,1990-01-07 07:13:00,1990-01-07 17:06:00,71,0,1,1990
7,1990-01-08,pre_2016,Chilas,Diamer,35.42,74.1,1250,7.76,4.80,6.10,...,1.36,34723.30,35616.88,25.14,1990-01-08 07:13:00,1990-01-08 17:07:00,1,0,1,1990
8,1990-01-09,pre_2016,Chilas,Diamer,35.42,74.1,1250,6.36,2.00,4.40,...,1.33,34726.09,35671.91,20.14,1990-01-09 07:13:00,1990-01-09 17:07:00,2,0,1,1990
9,1990-01-10,pre_2016,Chilas,Diamer,35.42,74.1,1250,6.56,3.20,5.20,...,1.32,31131.11,35729.45,64.14,1990-01-10 07:13:00,1990-01-10 17:08:00,3,0,1,1990
10,1990-01-11,pre_2016,Chilas,Diamer,35.42,74.1,1250,10.06,6.40,8.20,...,1.33,33531.27,35789.48,62.14,1990-01-11 07:13:00,1990-01-11 17:09:00,71,0,1,1990
11,1990-01-12,pre_2016,Chilas,Diamer,35.42,74.1,1250,12.06,8.40,10.20,...,1.54,34747.91,35852.66,37.14,1990-01-12 07:13:00,1990-01-12 17:10:00,71,0,1,1990
12,1990-01-13,pre_2016,Chilas,Diamer,35.42,74.1,1250,12.46,7.60,10.70,...,1.50,34477.18,35919.12,48.14,1990-01-13 07:12:00,1990-01-13 17:11:00,71,0,1,1990
13,1990-01-14,pre_2016,Chilas,Diamer,35.42,74.1,1250,5.76,-1.90,1.80,...,1.24,34463.52,35988.71,31.14,1990-01-14 07:12:00,1990-01-14 17:12:00,71,0,1,1990
14,1990-01-15,pre_2016,Chilas,Diamer,35.42,74.1,1250,6.16,0.30,3.40,...,1.36,28101.88,36061.30,58.14,1990-01-15 07:12:00,1990-01-15 17:13:00,3,0,1,1990
15,1990-01-16,pre_2016,Chilas,Diamer,35.42,74.1,1250,10.16,6.80,8.50,...,1.41,28210.03,36136.75,78.14,1990-01-16 07:12:00,1990-01-16 17:14:00,73,0,1,1990
16,1990-01-17,pre_2016,Chilas,Diamer,35.42,74.1,1250,9.86,7.50,8.80,...,1.01,143.73,36214.92,64.14,1990-01-17 07:11:00,1990-01-17 17:15:00,73,0,1,1990
17,1990-01-18,pre_2016,Chilas,Diamer,35.42,74.1,1250,11.46,9.60,10.60,...,1.21,2310.14,36295.68,86.14,1990-01-18 07:11:00,1990-01-18 17:16:00,73,0,1,1990
18,1990-01-19,pre_2016,Chilas,Diamer,35.42,74.1,1250,12.86,10.40,11.80,...,1.44,30534.18,36378.88,79.14,1990-01-19 07:11:00,1990-01-19 17:17:00,71,0,1,1990
19,1990-01-20,pre_2016,Chilas,Diamer,35.42,74.1,1250,14.06,12.10,12.80,...,1.45,27021.91,36464.40,80.14,1990-01-20 07:10:00,1990-01-20 17:18:00,73,0,1,1990
20,1990-01-21,pre_2016,Chilas,Diamer,35.42,74.1,1250,12.36,10.70,11.70,...,1.66,31319.76,36552.11,50.14,1990-01-21 07:10:00,1990-01-21 17:19:00,73,0,1,1990
21,1990-01-22,pre_2016,Chilas,Diamer,35.42,74.1,1250,9.26,2.80,6.80,...,1.46,35081.57,36641.86,11.14,1990-01-22 07:09:00,1990-01-22 17:20:00,2,0,1,1990
22,1990-01-23,pre_2016,Chilas,Diamer,35.42,74.1,1250,9.56,3.00,6.20,...,1.62,34977.64,36733.54,33.14,1990-01-23 07:09:00,1990-01-23 17:21:00,3,0,1,1990
23,1990-01-24,pre_2016,Chilas,Diamer,35.42,74.1,1250,12.56,7.00,9.40,...,1.84,35009.08,36827.02,75.14,1990-01-24 07:08:00,1990-01-24 17:22:00,3,0,1,1990
24,1990-01-25,pre_2016,Chilas,Diamer,35.42,74.1,1250,13.66,8.20,10.90,...,1.76,29771.00,36922.17,67.14,1990-01-25 07:08:00,1990-01-25 17:23:00,3,0,1,1990
25,1990-01-26,pre_2016,Chilas,Diamer,35.42,74.1,1250,11.26,9.30,10.50,...,1.12,2053.81,37018.87,80.14,1990-01-26 07:07:00,1990-01-26 17:24:00,73,0,1,1990
26,1990-01-27,pre_2016,Chilas,Diamer,35.42,74.1,1250,9.86,8.40,9.90,...,0.95,0.00,37116.99,78.14,1990-01-27 07:07:00,1990-01-27 17:25:00,75,0,1,1990
27,1990-01-28,pre_2016,Chilas,Diamer,35.42,74.1,1250,7.26,3.00,5.80,...,1.61,35150.86,37216.43,33.14,1990-01-28 07:06:00,1990-01-28 17:26:00,3,0,1,1990
28,1990-01-29,pre_2016,Chilas,Diamer,35.42,74.1,1250,3.36,-1.30,1.70,...,1.31,35190.18,37317.05,51.14,1990-01-29 07:05:00,1990-01-29 17:27:00,71,0,1,1990
29,1990-01-30,pre_2016,Chilas,Diamer,35.42,74.1,1250,6.26,4.10,4.80,...,1.61,36022.02,37418.74,75.14,1990-01-30 07:05:00,1990-01-30 17:28:00,71,0,1,1990
30,1990-01-31,pre_2016,Chilas,Diamer,35.42,74.1,1250,7.36,4.40,6.10,...,1.08,0.00,37521.47,70.14,1990-01-31 07:04:00,1990-01-31 17:29:00,73,0,1,1990
31,1990-02-01,pre_2016,Chilas,Diamer,35.42,74.1,1250,6.08,0.81,3.72,...,1.73,38418.40,37626.20,26.84,1990-02-01 07:03:00,1990-02-01 17:30:00,71,0,2,1990
32,1990-02-02,pre_2016,Chilas,Diamer,35.42,74.1,1250,3.78,-3.19,0.62,...,1.51,38125.85,37733.18,29.84,1990-02-02 07:02:00,1990-02-02 17:31:00,3,0,2,1990
33,1990-02-03,pre_2016,Chilas,Diamer,35.42,74.1,1250,7.48,1.11,4.92,...,1.50,17741.34,37842.26,78.84,1990-02-03 07:02:00,1990-02-03 17:32:00,71,0,2,1990
34,1990-02-04,pre_2016,Chilas,Diamer,35.42,74.1,1250,8.18,4.91,6.12,...,1.77,38761.09,37953.30,66.84,1990-02-04 07:01:00,1990-02-04 17:33:00,71,0,2,1990
35,1990-02-05,pre_2016,Chilas,Diamer,35.42,74.1,1250,8.28,3.41,5.82,...,1.60,29897.73,38066.17,78.84,1990-02-05 07:00:00,1990-02-05 17:34:00,71,0,2,1990
36,1990-02-06,pre_2016,Chilas,Diamer,35.42,74.1,1250,9.68,5.51,8.02,...,1.43,16040.15,38180.71,77.84,1990-02-06 06:59:00,1990-02-06 17:35:00,73,0,2,1990
37,1990-02-07,pre_2016,Chilas,Diamer,35.42,74.1,1250,12.68,9.91,11.12,...,1.61,9548.68,38296.79,78.84,1990-02-07 06:58:00,1990-02-07 17:36:00,73,0,2,1990
38,1990-02-08,pre_2016,Chilas,Diamer,35.42,74.1,1250,13.48,9.21,11.12,...,2.15,36979.04,38414.28,52.84,1990-02-08 06:57:00,1990-02-08 17:37:00,71,0,2,1990
39,1990-02-09,pre_2016,Chilas,Diamer,35.42,74.1,1250,10.98,5.71,9.02,...,2.24,39905.55,38533.04,16.84,1990-02-09 06:56:00,1990-02-09 17:38:00,71,0,2,1990

In [13]:
# mean and std per station calculation & merge back onto main dataframe
station_stats = era5.groupby('station')['precipitation_sum'].agg(['mean', 'std'])

era5 = era5.merge(station_stats, on='station', suffixes=('', '_station'))

#threshold calculation
era5['extreme_threshold'] = era5['mean'] + 2 * era5['std']

#is_extreme label created 
era5['is_extreme'] = era5['precipitation_sum'] > era5['extreme_threshold']

era5['is_extreme'] = era5['precipitation_sum'] > era5['extreme_threshold']
era5['is_extreme'] = era5['is_extreme'].astype(int)  # convert True/False to 1/0

print(era5['is_extreme'].value_counts())
print(era5['is_extreme'].value_counts(normalize=True))  # shows as percentages

is_extreme
0    61054
1     2866
Name: count, dtype: int64
is_extreme
0    0.955163
1    0.044837
Name: proportion, dtype: float64

In [14]:
era5['is_extreme'].value_counts()

is_extreme
0    61054
1     2866
Name: count, dtype: int64

In [15]:
era5[['station', 'date']].head(10)

  station        date
0  Chilas  1990-01-01
1  Chilas  1990-01-02
2  Chilas  1990-01-03
3  Chilas  1990-01-04
4  Chilas  1990-01-05
5  Chilas  1990-01-06
6  Chilas  1990-01-07
7  Chilas  1990-01-08
8  Chilas  1990-01-09
9  Chilas  1990-01-10

In [16]:
# Lag features (grouped by station, so no cross-contamination)
era5['precip_hours_lag1'] = era5.groupby('station')['precipitation_hours'].shift(1)
era5['cloud_cover_lag1'] = era5.groupby('station')['cloud_cover_mean'].shift(1)
era5['cloud_cover_roll3'] = era5.groupby('station')['cloud_cover_mean'].transform(lambda x: x.rolling(3).mean())
era5['wind_speed_roll3'] = era5.groupby('station')['wind_speed_10m_max'].transform(lambda x: x.rolling(3).mean())

# Check for NaNs created by shift/rolling
print(era5[['precip_hours_lag1', 'cloud_cover_lag1', 'cloud_cover_roll3', 'wind_speed_roll3']].isna().sum())

precip_hours_lag1     5
cloud_cover_lag1      5
cloud_cover_roll3    10
wind_speed_roll3     10
dtype: int64

In [17]:
era5 = era5.dropna(subset=['precip_hours_lag1', 'cloud_cover_lag1', 'cloud_cover_roll3', 'wind_speed_roll3'])
print(era5.shape)

(63910, 40)

In [18]:
columns_to_drop = [
    'date', 'era5_period', 'weather_code', 'sunrise', 'sunset',
    'bias_corrected', 'station', 'district',
    'precipitation_sum', 'rain_sum', 'snowfall_sum',
    'mean', 'std', 'extreme_threshold'
]

era5 = era5.drop(columns=columns_to_drop)
print(era5.columns.tolist())
print(era5.shape)

['lat', 'lon', 'elevation_m', 'temperature_2m_max', 'temperature_2m_min', 'temperature_2m_mean', 'apparent_temperature_max', 'apparent_temperature_min', 'apparent_temperature_mean', 'precipitation_hours', 'wind_speed_10m_max', 'wind_speed_10m_mean', 'wind_gusts_10m_max', 'wind_direction_10m_dominant', 'shortwave_radiation_sum', 'et0_fao_evapotranspiration', 'sunshine_duration', 'daylight_duration', 'cloud_cover_mean', 'month', 'year', 'is_extreme', 'precip_hours_lag1', 'cloud_cover_lag1', 'cloud_cover_roll3', 'wind_speed_roll3']
(63910, 26)

In [19]:
train = era5[era5['year'] <= 2018]
test = era5[era5['year'] >= 2019]

X_train = train.drop(columns=['is_extreme'])
y_train = train['is_extreme']
X_test = test.drop(columns=['is_extreme'])
y_test = test['is_extreme']

print(X_train.shape, X_test.shape)
print(train['is_extreme'].mean(), test['is_extreme'].mean())

(52950, 25) (10960, 25)
0.04304060434372049 0.053558394160583944

In [31]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)  # note: raw X_train, not X_train_scaled, trees don't need scaling

RandomForestClassifier(class_weight='balanced', n_estimators=200, n_jobs=-1,
                       random_state=42)

In [32]:
y_pred_rf = rf.predict(X_test)
y_pred_proba_rf = rf.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97     10373
           1       0.73      0.13      0.22       587

    accuracy                           0.95     10960
   macro avg       0.84      0.56      0.60     10960
weighted avg       0.94      0.95      0.93     10960

In [33]:
for t in [0.2, 0.3, 0.4, 0.5, 0.6, 0.7]:
    y_pred_t = (y_pred_proba_rf > t).astype(int)
    p = precision_score(y_test, y_pred_t)
    r = recall_score(y_test, y_pred_t)
    f1 = f1_score(y_test, y_pred_t)
    print(f"Threshold {t}: precision={p:.3f}, recall={r:.3f}, f1={f1:.3f}")

Threshold 0.2: precision=0.593, recall=0.532, f1=0.561
Threshold 0.3: precision=0.674, recall=0.359, f1=0.469
Threshold 0.4: precision=0.677, recall=0.218, f1=0.330
Threshold 0.5: precision=0.726, recall=0.131, f1=0.222
Threshold 0.6: precision=0.745, recall=0.060, f1=0.110
Threshold 0.7: precision=0.826, recall=0.032, f1=0.062

In [34]:
import pandas as pd

importances = pd.Series(rf.feature_importances_, index=X_train.columns).sort_values(ascending=False)
print(importances)

precipitation_hours            0.341047
cloud_cover_mean               0.136525
sunshine_duration              0.092899
cloud_cover_roll3              0.056670
precip_hours_lag1              0.053697
cloud_cover_lag1               0.031594
shortwave_radiation_sum        0.029310
wind_gusts_10m_max             0.027018
apparent_temperature_min       0.023236
temperature_2m_min             0.021300
daylight_duration              0.020865
et0_fao_evapotranspiration     0.016736
apparent_temperature_mean      0.015415
wind_direction_10m_dominant    0.014811
wind_speed_10m_mean            0.014384
wind_speed_roll3               0.014006
temperature_2m_mean            0.013169
temperature_2m_max             0.013009
wind_speed_10m_max             0.012989
apparent_temperature_max       0.012422
month                          0.009514
lat                            0.009371
year                           0.008714
elevation_m                    0.005946
lon                            0.005353
dtype: float64